# NumPy (Numeric Python)

<b> Python Arrays<b>

In [5]:
import array
my_array = array.array('i',[ 1, 2, 3, 4])

In [6]:
type(my_array)

array.array

In [7]:
my_float_array = array.array('f', [1.2, 3.4])
my_float_array

array('f', [1.2000000476837158, 3.4000000953674316])

<b> NumPy arrays<b>

In [9]:
import numpy 

In [12]:
#numpy.array()

In [10]:
import numpy as np 

In [13]:
#np.array()

In [15]:
list1 = [ 1, 3, 4, 8 ,5]
np.array(list1)

array([1, 3, 4, 8, 5])

In [19]:
int_list = [ 1, 3, 4, 8 ,5]
my_np_array = np.array(int_list)
my_np_array

array([1, 3, 4, 8, 5])

In [20]:
type(my_np_array)

numpy.ndarray

In [21]:
float_list = [ 1.1, 2.3, 3.4]
my_np_float_array = np.array(float_list)
my_np_float_array

array([1.1, 2.3, 3.4])

In [22]:
type(my_np_float_array)

numpy.ndarray

In [24]:
mixed_element_list = [1, 1.1, 2, 2.3, 3, 3.7]
my_mixed_array = np.array(mixed_element_list)
my_mixed_array

array([1. , 1.1, 2. , 2.3, 3. , 3.7])

In [26]:
int_list = [ 1, 3, 4, 8 ,5]
my_np_array = np.array(int_list, dtype=int)
my_np_array

array([1, 3, 4, 8, 5])

In [28]:
to_back_list = my_np_array.tolist()
to_back_list

[1, 3, 4, 8, 5]

<b> Propeties of NumPy Array <B>

In [29]:
my_np_array

array([1, 3, 4, 8, 5])

In [30]:
my_np_array.dtype

dtype('int32')

In [31]:
my_np_array.ndim

1

In [32]:
my_np_array.shape

(5,)

In [33]:
my_np_array.size

5

<b> Prepolulated arrays <b>

In [36]:
zeros = np.zeros(6)
zeros

array([0., 0., 0., 0., 0., 0.])

In [37]:
zeros.dtype

dtype('float64')

In [39]:
zeroes_ints = np.zeros(6, dtype=int)
zeroes_ints

array([0, 0, 0, 0, 0, 0])

In [40]:
zeroes_ints.dtype

dtype('int32')

In [42]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [44]:
ones_ints = np.ones(3, dtype=int)
ones_ints

array([1, 1, 1])

In [45]:
np.empty(10)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 3.56042035e-307,
       4.00535364e-307, 1.78019082e-306, 8.45584427e-307, 8.45602762e-307,
       7.56599128e-307, 9.34600963e-307])

In [46]:
arange_array = np.arange(1, 10)
arange_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a1 = np.arange(5, 50, 5)
a1

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [51]:
ln1 = np.linspace(1, 5, 5)
ln1

array([1., 2., 3., 4., 5.])

In [52]:
ln1 = np.linspace(1, 5, 3)
ln1

array([1., 3., 5.])

<b> 2 dimentionsal arrays <b>

In [53]:
l1 = [ 1, 2, 3]
l2 = [4, 5, 6]
l3 = [7, 8, 9 ]

two_d_array = np.array([l1, l2, l3])
two_d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]

a2 = np.array([l1, l2])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
two_d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
two_d_array.dtype

dtype('int32')

In [57]:
two_d_array.ndim

2

In [58]:
two_d_array.shape

(3, 3)

In [59]:
a2.shape

(2, 3)

In [61]:
two_d_array.size

9