# NumPy Computations

In [2]:
import numpy as np

In [6]:
l1 = [ 1, 2, 3, 4,5 ]
a1 = np.array(l1)
l1
a1

array([1, 2, 3, 4, 5])

In [8]:
l2 = [[1,2,3], [4, 5, 6]]
a2 = np.array(l2)
a2

array([[1, 2, 3],
       [4, 5, 6]])

<b> Ways to access the array elements<b>

In [10]:
a1

array([1, 2, 3, 4, 5])

In [12]:
a1[0]

1

In [14]:
a1[2]

3

In [16]:
a1[-1]

5

In [18]:
a1[3] = 4444
a1

array([   1,    2,    3, 4444,    5])

In [20]:
a1

array([   1,    2,    3, 4444,    5])

In [22]:
a1[:]

array([   1,    2,    3, 4444,    5])

In [24]:
a1[:2]

array([1, 2])

In [26]:
a1[3:]

array([4444,    5])

In [28]:
a1[::2]

array([1, 3, 5])

In [30]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a2[0,0] r0, c0

1

In [34]:
a2[0,1]

2

In [36]:
a2[1,2]

6

In [38]:
a2[:, : ]

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
a2[:0, : 3]

array([], shape=(0, 3), dtype=int32)

In [52]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a1

array([   1,    2,    3, 4444,    5])

In [56]:
a_sub = a1[:3]
a_sub

array([1, 2, 3])

In [58]:
a_sub[0] = 89
a_sub

array([34,  2,  3])

In [24]:
a1

array([  34,    2,    3, 4444,    5])

In [60]:
a_copy = a1.copy()
a_copy

array([  34,    2,    3, 4444,    5])

In [64]:
a_copy[0] = 4567
print(a_copy)

print(a1)

[4567    2    3 4444    5]
[  34    2    3 4444    5]


In [66]:
a1[0]=789

In [68]:
a_copy

array([4567,    2,    3, 4444,    5])

<b> Reshaping<b>

In [75]:
a1 
print("a1---->", a1)
print(a1.shape)
print(a1.ndim)

a1----> [ 789    2    3 4444    5]
(5,)
1


In [73]:
a1_reshaped = a1.reshape(5, 1)
print("a1_reshaped-----> \n", a1_reshaped)
print("\n", a1_reshaped.shape)
print(a1_reshaped.ndim)

a1_reshaped-----> 
 [[ 789]
 [   2]
 [   3]
 [4444]
 [   5]]

 (5, 1)
2


In [77]:
a1_reshaped = a1.reshape(1, 5)
print("a1_reshaped-----> \n", a1_reshaped)
print("\n", a1_reshaped.shape)
print(a1_reshaped.ndim)

a1_reshaped-----> 
 [[ 789    2    3 4444    5]]

 (1, 5)
2


<b> Computations - Arithmetic <b>

In [79]:
a1

array([ 789,    2,    3, 4444,    5])

In [81]:
sum(a1)

5243

In [87]:
a11 = np.random.randint(1, 100, size=1000)
a11.size
a11

array([67, 80, 44, 79, 45, 45, 55,  9, 71, 82, 62, 65, 72, 39, 43,  1, 14,
       63,  7, 73, 29, 57, 37, 26, 65, 63, 13,  7, 14, 17, 90, 18, 95, 31,
        1, 68, 17, 18, 59, 58, 51, 31, 19, 77, 51,  1, 15,  1, 45, 81, 77,
       68, 37, 24, 67,  5, 31, 87, 68, 22, 39, 45, 39, 89, 24, 92, 25, 31,
        2, 29, 33, 85, 83, 15, 19, 84, 54, 50, 63, 73, 77, 63, 91, 27, 68,
       87, 56, 80, 14, 23, 77, 19, 80, 60, 34, 32, 73, 85, 31,  1, 43, 90,
       48, 57, 86, 52,  1, 80, 83, 60, 32, 65, 85, 41, 31, 62, 29, 62, 69,
       93, 34, 87, 31, 20, 80, 89,  2, 80, 29, 22, 54, 98, 29, 65, 90, 77,
       90, 90, 93, 63, 27,  9, 73, 42, 15, 76, 78, 38, 76, 67, 92, 81, 42,
       13, 90, 92, 35, 29, 89, 60,  9, 55, 74, 11,  5,  3, 75, 87,  2, 96,
       85, 41, 50, 73, 12, 67, 59, 33, 44, 43, 80, 49,  3, 66, 72, 25, 20,
       68, 51, 66, 16, 52, 84, 84, 33, 68, 42, 59, 38, 25,  9, 84, 25, 48,
       77, 41, 98, 57, 70, 50, 89, 30, 93, 36, 11, 86, 66,  5, 32, 21, 97,
       18, 40, 74, 56, 90

In [89]:
sum(a11)

51192

In [91]:
np.sum(a11)

51192

In [93]:
%timeit sum(a11)

130 μs ± 13.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [47]:
%timeit np.sum(a11)

3.83 µs ± 171 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
a11

In [95]:
a1

array([ 789,    2,    3, 4444,    5])

In [143]:
a1 + 5

array([ 794,    7,    8, 4449,   10])

In [99]:
a1 ** 2

array([  622521,        4,        9, 19749136,       25])

In [101]:
np.add(a1, 5)

array([ 794,    7,    8, 4449,   10])

In [103]:
a1 * 4

array([ 3156,     8,    12, 17776,    20])

In [105]:
np.power(a1, 3)

array([ 491169069,          8,         27, 1865814464,        125],
      dtype=int32)

In [107]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
a2 + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [111]:
a2 - 5

array([[-4, -3, -2],
       [-1,  0,  1]])

In [121]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
np.sum(a2)

21

In [123]:
np.sum(a2, axis=0) # For tomorrow

array([5, 7, 9])

<b>If we calculate np.sum(a2, axis=0), we are summing along the rows (column-wise summation).</b> <br>

Column-wise Summation (axis=0): <br>

First column: 1+4=5 <br>
Second column: 2+5=7 <br>
Third column: 3+6=9

In [125]:
np.sum(a2, axis=1)

array([ 6, 15])

<b>If we calculate np.sum(a2, axis=1), we are summing along the columns (row-wise summation)..</b> <br>

Column-wise Summation (axis=0): <br>

First row: 1+2+3=6 <br>
Second row: 4+5+6= 15 <br>


<b>Computations - Comparisons<b>

In [131]:
a1

array([ 789,    2,    3, 4444,    5])

In [66]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
type(a2)

numpy.ndarray

In [127]:
a1 == 5

array([False, False, False, False,  True])

In [129]:
a1 != 45

array([ True,  True,  True,  True,  True])

In [133]:
print("a1---->", a1)
np.sum(a1 == 5)

a1----> [ 789    2    3 4444    5]


1

In [135]:
np.sum(a1)

5243

In [139]:
a1+5

array([ 794,    7,    8, 4449,   10])

In [141]:
np.sum(a1)+5

5248

In [149]:
np.sum(a1 < 500)

3

In [153]:
print("a1---->", a1)
np.all(a1 < 5000)

a1----> [ 789    2    3 4444    5]


True

In [151]:
a1

array([ 789,    2,    3, 4444,    5])

In [155]:
np.any(a1 > 5000)

False

In [157]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [159]:
np.sum(a2 < 100 )

6

In [80]:
np.greater(a1, 5)

array([ True, False, False,  True, False])

<b> Computations - Aggregations <b>

In [81]:
a1

array([  34,    2,    3, 4444,    5])

In [82]:
a1.sum()

4488

In [83]:
np.sum(a1)

4488

In [84]:
a1.min()

2

In [85]:
a1.max()

4444

In [86]:
a1.mean()

897.6

In [87]:
a1.std()

1773.2400401524887

In [88]:
a1.var()

3144380.24

In [89]:
a2.sum()

21

In [90]:
a2.min()

1

In [91]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
np.sum(a2, axis=0)

array([5, 7, 9])

In [93]:
np.sum(a2, axis=1)

array([ 6, 15])

In [94]:
np.min(a2, axis=0)

array([1, 2, 3])

<b>Computations - Boolean operators<b>

In [97]:
a1

array([  34,    2,    3, 4444,    5])

In [98]:
a1 > 5

array([ True, False, False,  True, False])

In [100]:
np.any(a1 > 5)

True

In [101]:
np.any((a1 > 5) & (a1 < 10) )

False

In [104]:
np.sum((a1 > 5) &  (a1 < 10))

0

In [105]:
np.sum( (a1 > 5 ) | (a1 < 10))

5