# Data Exploration using Pandas

In [ ]:
import pandas as pd
import numpy as np

Task - <br>

- Importing the dataset
- Clean, format, transform that dataframe
- Grouping / Merging
- Export the results / data frames

# <b> Importing the dataset<b>

In [2]:
bikes = pd.read_csv("bike_shairing_hourly.csv")

In [3]:
bikes.head()

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1

In [5]:
bikes.tail(2)

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
17377    17378  2012-12-31       1   1    12  22        0        1   
17378    17379  2012-12-31       1   1    12  23        0        1   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
17377           1           1  0.26  0.2727  0.56     0.1343      13   
17378           1           1  0.26  0.2727  0.65     0.1343      12   

       registered  cnt  
17377          48   61  
17378          37   49

In [6]:
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
instant       17379 non-null int64
dteday        17379 non-null object
season        17379 non-null int64
yr            17379 non-null int64
mnth          17379 non-null int64
hr            17379 non-null int64
holiday       17379 non-null int64
weekday       17379 non-null int64
workingday    17379 non-null int64
weathersit    17379 non-null int64
temp          17379 non-null float64
atemp         17379 non-null float64
hum           17379 non-null float64
windspeed     17379 non-null float64
casual        17379 non-null int64
registered    17379 non-null int64
cnt           17379 non-null int64
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB


In [7]:
bikes.shape

(17379, 17)

In [8]:
bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [9]:
bikes.dtypes


instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

In [102]:
bikes.describe()

season            yr          mnth            hr       holiday  \
count  17379.000000  17379.000000  17379.000000  17379.000000  17379.000000   
mean       2.501640      0.502561      6.537775     11.546752      0.028770   
std        1.106918      0.500008      3.438776      6.914405      0.167165   
min        1.000000      0.000000      1.000000      0.000000      0.000000   
25%        2.000000      0.000000      4.000000      6.000000      0.000000   
50%        3.000000      1.000000      7.000000     12.000000      0.000000   
75%        3.000000      1.000000     10.000000     18.000000      0.000000   
max        4.000000      1.000000     12.000000     23.000000      1.000000   

            weekday    workingday    weathersit          temp         atemp  \
count  17379.000000  17379.000000  17379.000000  17379.000000  17379.000000   
mean       3.003683      0.682721      1.425283      0.496987      0.475775   
std        2.005771      0.465431      0.639357      0.192556      0.171850   
min        0.000000      0.000000      1.000000      0.020000      0.000000   
25%        1.000000      0.000000      1.000000      0.340000      0.333300   
50%        3.000000      1.000000      1.000000      0.500000      0.484800   
75%        5.000000      1.000000      2.000000      0.660000      0.621200   
max        6.000000      1.000000      4.000000      1.000000      1.000000   

                hum     windspeed        casual    registered          year  
count  17379.000000  17379.000000  17379.000000  17379.000000  17379.000000  
mean       0.627229      0.190098     35.676218    153.786869   2011.502561  
std        0.192930      0.122340     49.305030    151.357286      0.500008  
min        0.000000      0.000000      0.000000      0.000000   2011.000000  
25%        0.480000      0.104500      4.000000     34.000000   2011.000000  
50%        0.630000      0.194000     17.000000    115.000000   2012.000000  
75%        0.780000      0.253700     48.000000    220.000000   2012.000000  
max        1.000000      0.850700    367.000000    886.000000   2012.000000

In [104]:
bikes.season.describe()

count    17379.000000
mean         2.501640
std          1.106918
min          1.000000
25%          2.000000
50%          3.000000
75%          3.000000
max          4.000000
Name: season, dtype: float64

# <b> Clean, format, transform that dataframe<b>

In [11]:
bikes.columns


Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [12]:
bikes.instant.unique()

array([    1,     2,     3, ..., 17377, 17378, 17379], dtype=int64)

In [ ]:
bikes.dteday.unique()

In [14]:
bikes.season.unique()

array([1, 2, 3, 4], dtype=int64)

In [16]:
bikes.yr.unique()

array([0, 1], dtype=int64)

In [17]:
bikes["mnth"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [18]:
bikes.hr.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int64)

In [19]:
bikes.holiday.unique()

array([0, 1], dtype=int64)

In [20]:
bikes.weekday.unique()

array([6, 0, 1, 2, 3, 4, 5], dtype=int64)

In [21]:
bikes.workingday.unique()

array([0, 1], dtype=int64)

In [23]:
bikes.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [24]:
bikes.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [25]:
bikes.instant.isnull().sum()

0

In [26]:
bikes.duplicated().sum()

0

In [27]:
bikes.instant.duplicated().sum()

0

In [28]:
bikes.dteday.duplicated().sum()

16648

In [30]:
bikes = bikes.dropna()

In [32]:
bikes.dropna(inplace=True)

In [33]:
bikes.drop_duplicates(subset="instant", inplace=True)

In [ ]:
bikes.fillna(9)

In [ ]:
bikes.instant.fillna(0)

In [38]:
bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

In [40]:
dte = pd.to_datetime(bikes.dteday)

In [41]:
type(dte)

pandas.core.series.Series

In [ ]:
dte.dt.year

In [ ]:
dte.dt.month

In [ ]:
dte.dt.day

In [ ]:
dte.dt.week

In [ ]:
dte.dt.weekday

In [ ]:
dte

In [48]:
year = dte.dt.year

In [49]:
type(year)

pandas.core.series.Series

In [50]:
bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [51]:
bikes["year"] = year

In [52]:
bikes.columns


Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt', 'year'],
      dtype='object')

In [56]:
bikes = bikes.drop("instant", axis=1)

In [57]:
bikes.head()

dteday  season  yr  mnth  hr  holiday  weekday  workingday  weathersit  \
0  2011-01-01       1   0     1   0        0        6           0           1   
1  2011-01-01       1   0     1   1        0        6           0           1   
2  2011-01-01       1   0     1   2        0        6           0           1   
3  2011-01-01       1   0     1   3        0        6           0           1   
4  2011-01-01       1   0     1   4        0        6           0           1   

   temp   atemp   hum  windspeed  casual  registered  cnt  year  
0  0.24  0.2879  0.81        0.0       3          13   16  2011  
1  0.22  0.2727  0.80        0.0       8          32   40  2011  
2  0.22  0.2727  0.80        0.0       5          27   32  2011  
3  0.24  0.2879  0.75        0.0       3          10   13  2011  
4  0.24  0.2879  0.75        0.0       0           1    1  2011

bikes.columns

In [59]:
bikes.drop("cnt", axis=1, inplace=True)

In [60]:
bikes.columns

Index(['dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'year'],
      dtype='object')

# <b>  Grouping / Merging <b>

In [62]:
bikes.head(2)

dteday  season  yr  mnth  hr  holiday  weekday  workingday  weathersit  \
0  2011-01-01       1   0     1   0        0        6           0           1   
1  2011-01-01       1   0     1   1        0        6           0           1   

   temp   atemp   hum  windspeed  casual  registered  year  
0  0.24  0.2879  0.81        0.0       3          13  2011  
1  0.22  0.2727  0.80        0.0       8          32  2011

In [63]:
bikes_2011 = bikes[year == 2011]

In [ ]:
bikes_2011.head()

In [66]:
bikes_2011 = bikes[bikes.yr == 0]

<b> Grouping<b>

In [67]:
#sum(casual) group by season
df_by_seasons = bikes.groupby("season")

In [69]:
type(df_by_seasons)

pandas.core.groupby.generic.DataFrameGroupBy

In [74]:
df_by_seasons.casual.sum()

season
1     60622
2    203522
3    226091
4    129782
Name: casual, dtype: int64

In [76]:
df_by_seasons["casual"].sum()

season
1     60622
2    203522
3    226091
4    129782
Name: casual, dtype: int64

In [77]:
type(df_by_seasons.casual.sum())

pandas.core.series.Series

In [78]:
series_casual = df_by_seasons.casual.sum()

In [79]:
series_registered = df_by_seasons.registered.sum()

In [80]:
series_registered

season
1    410726
2    715067
3    835038
4    711831
Name: registered, dtype: int64

<b> concat<b>

In [81]:
frames = [series_casual, series_registered]

In [84]:
df = pd.concat(frames, axis=1)

In [85]:
df

casual  registered
season                    
1        60622      410726
2       203522      715067
3       226091      835038
4       129782      711831

In [86]:
df["total"] = df.casual + df.registered

In [87]:
df

casual  registered    total
season                             
1        60622      410726   471348
2       203522      715067   918589
3       226091      835038  1061129
4       129782      711831   841613

<b> merge <b>

In [88]:
series_casual

season
1     60622
2    203522
3    226091
4    129782
Name: casual, dtype: int64

In [89]:
series_registered

season
1    410726
2    715067
3    835038
4    711831
Name: registered, dtype: int64

In [90]:
df_casual = pd.DataFrame(series_casual)

In [91]:
df_casual

casual
season        
1        60622
2       203522
3       226091
4       129782

In [92]:
df_registered = pd.DataFrame(series_registered)

In [93]:
df_registered

registered
season            
1           410726
2           715067
3           835038
4           711831

In [98]:
df2 = pd.merge(df_casual, df_registered, on=["season"])

In [99]:
df2

casual  registered
season                    
1        60622      410726
2       203522      715067
3       226091      835038
4       129782      711831

# <b> Export the results / data frames <b>

In [100]:
df

casual  registered    total
season                             
1        60622      410726   471348
2       203522      715067   918589
3       226091      835038  1061129
4       129782      711831   841613

In [101]:
df.to_csv("outcome.csv")